version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    restart: always

  web:
    build: .
    command: python ./init_db.py
    ports:
      - "5000:5000"
    volumes:
      - .:/test_project
    links:
      - db